{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "target-service.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "target-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: "CHANGE_ME_IN_PRODUCTION"  # Use sealed-secrets ou external-secrets em produção
{{- end }}
