apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/seu-usuario/seu-gitops-repo.git
    targetRevision: main
    path: gitops/helm/auth-service
    helm:
      releaseName: auth-service
      values: |
        image:
          repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/auth-service
          tag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
