apiVersion: v2
name: target-service
description: Target Service - Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - targets
  - python
maintainers:
  - name: Your Organization
    email: team@example.com
