apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/andre-svager/specialization-stage3.git
  password: ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxx  # GitHub token
  username: not_used
---
apiVersion: v1
kind: Secret
metadata:
  name: ecr-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: kubernetes.io/dockercfg
stringData:
  .dockercfg: |
    {
      "123456789012.dkr.ecr.us-east-1.amazonaws.com": {
        "auth": "YOUR_BASE64_ENCODED_CREDENTIALS"
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: git-deploy-key
  namespace: argocd
type: Opaque
stringData:
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    # Adicione sua chave SSH privada aqui
    -----END OPENSSH PRIVATE KEY-----
