apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/andre-svager/specialization-stage3.git
  password: ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxx  # GitHub token
  username: not_used
---
apiVersion: v1
kind: Secret
metadata:
  name: ecr-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "973397181776.dkr.ecr.us-east-1.amazonaws.com": {
          "username": "AWS",
          "password": "AKIA6FIX6IVARH43A3X:6mJjwR87RWQdgPY4Czb2wzwErMY47n7qNWjGLyYh",
          "auth": "QVdTOkFLSUE2RklYNklWQVJINDNBM1g6Nm1KandSODdSV1FkZ1BZNEN6YjJ3endFck1ZNDduN3FOV2pHTHlZaA=="
        }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: git-deploy-key
  namespace: argocd
type: Opaque
stringData:
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    # Adicione sua chave SSH privada aqui
    -----END OPENSSH PRIVATE KEY-----
